### ISSUE TITLE
python版本有问题？

### ISSUE THREAD

**Issue by kiok1210** [jinhucheung/letscertbot#26]
[root@ecs-6289 letscertbot]# python ./bin/manual.py --test --domain your.example.com --dns aliyun
start to test your.example.com in DNS aliyun API
add TXT record(domain=example.com, rr=_acme-challenge.your, value=Ich0vX28RDdVOWaC) to aliyun DNS
ERROR:logger:aliyun#__request raise urllib2.HTTPError: HTTP Error 400: Bad Request
HTTP Error 400: Bad Request

[root@ecs-6289 letscertbot]# python --version
Python 2.7.5

**Comment by jinhucheung** [comment]
@kiok1210 你好，我这边尝试了下暂未发现此问题。

执行上述命令前需要在配置文件中设置好阿里云 Access Key 以及确认拥有测试域名。

**Comment by jinhucheung** [comment]
@kiok1210 如果没什么问题，我这边先关闭了。后续发现了该问题，再重新打开 :heart:
