### ISSUE TITLE
能否提供DOCKER IMAGE下载

### ISSUE THREAD

**Issue by ajdan4q** [jinhucheung/letscertbot#28]
build image会在以下卡住，原因你懂的，

> Building app
Step 1/5 : FROM certbot/certbot
 ---> 0091bcdbf8c6
Step 2/5 : RUN apk update && apk add openssh sshpass man man-pages
 ---> Running in 15993ed4430a
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz

**Comment by jinhucheung** [comment]
@ajdan4q 你好，可以在下面链接获取到镜像

https://pan.baidu.com/s/1XtnIEN5kS1OVFiixuYwdrw  (提取码: ddex)

然后执行以下命令加载：

```sh
$ docker load < letscertbot.tar
```

**Comment by jinhucheung** [comment]
如果百度网盘操作麻烦，也可以在 Gitee 上下载，下载后需要解压下

https://gitee.com/jimcheung/letscertbot/attach_files

**Comment by ajdan4q** [comment]
好的，感谢。
