### ISSUE TITLE
报使用错误：Unable to register an account with ACME server

### ISSUE THREAD

**Issue by shenqihui** [jinhucheung/letscertbot#30]
![image](https://user-images.githubusercontent.com/4081063/116047327-8a4cc100-a6a6-11eb-8f34-751a2e828ec4.png)
看样子是邮箱问题，已经换过了gmail、qq、还有自己域名下的邮箱试过，都失败。

已经配置了 email 和 阿里云的key。

调用测试版本
`docker-compose run --rm app manual --test --domain www.a.cn --dns aliyun` 正常

调用
`docker-compose run --rm app obtain -d a.cn -d "*.a.cn"`

求解答，谢谢。

**Comment by jinhucheung** [comment]
@shenqihui 谢谢反馈！

**Comment by jinhucheung** [comment]
抱歉，无法重现这个问题，应该是邮箱的问题

**Comment by shenqihui** [comment]
最后我放弃了。。。自己装certbot然后弄pip插件。
